### ISSUE TITLE
Question: Directly open the Review section (edit mode use-case)

### ISSUE THREAD

**Issue by popofibo** [codrops/FullscreenForm#2]
I couldn't figure out (or need pointers to) the ability to open the 'Review' mode for the pre-filled fields in edit mode. Pre-fill can easily be taken care of on the server side (I'm guessing) but direct 'review' mode is what I'm struggling with. I understand this is quite specific but any pointers or the starting points would be extremely helpful.

Thanks!

**Comment by ghost** [comment]
You did it?
